### ISSUE TITLE
simulation.launch spawn model not working

### ISSUE THREAD

**Issue by dallinbriggs** [BYU-MAGICC/fcu_sim#14]
Fixedwing.launch seems to work just fine, but simulation.launch will launch the factory world, but it fails to spawn shredder. This is for the kinetic branch.

process[gazebo-2]: started with pid [31596]
process[gazebo_gui-3]: started with pid [31615]
process[spawn_shredder-4]: started with pid [31625]
spawn_model script started
[gazebo-2] process has died [pid 31596, exit code 255, cmd /opt/ros/kinetic/lib/gazebo_ros/gzserver -e ode /home/dallin/rosplane_ws/src/fcu_sim/fcu_sim/worlds/powerplant.world __name:=gazebo __log:=/home/dallin/.ros/log/9e6975a2-90a3-11e6-b67e-2c44fd1061c5/gazebo-2.log].
log file: /home/dallin/.ros/log/9e6975a2-90a3-11e6-b67e-2c44fd1061c5/gazebo-2*.log
[INFO] [WallTime: 1476294310.208940] [0.000000] Loading model xml from ros parameter
[INFO] [WallTime: 1476294310.211014] [0.000000] Waiting for service /gazebo/spawn_urdf_model

**Comment by superjax** [comment]
Try simple.launch.  I tried it last night, and it seemed to be working.  I'll go ahead and try again when I get home tonight.

**Comment by dallinbriggs** [comment]
I tried that also and it still doesn't spawn a MAV. 

process[spawn_shredder-4]: started with pid [1371]
process[rc-5]: started with pid [1372]
ERROR: cannot launch node of type [joy/joy_node]: joy
ROS path [0]=/opt/ros/kinetic/share/ros
ROS path [1]=/home/dallin/rosplane_ws/src
ROS path [2]=/opt/ros/kinetic/share
ROS path [3]=/opt/ros/kinetic/stacks
ERROR: cannot launch node of type [ros_copter/controller]: ros_copter
ROS path [0]=/opt/ros/kinetic/share/ros
ROS path [1]=/home/dallin/rosplane_ws/src
ROS path [2]=/opt/ros/kinetic/share
ROS path [3]=/opt/ros/kinetic/stacks
process[fpv-8]: started with pid [1373]
init done
spawn_model script started
[gazebo-2] process has died [pid 1357, exit code 255, cmd /opt/ros/kinetic/lib/gazebo_ros/gzserver -u -e ode /home/dallin/rosplane_ws/src/fcu_sim/fcu_sim/worlds/better_crazy_world.sdf __name:=gazebo __log:=/home/dallin/.ros/log/b52aa4f8-90a5-11e6-b67e-2c44fd1061c5/gazebo-2.log].
log file: /home/dallin/.ros/log/b52aa4f8-90a5-11e6-b67e-2c44fd1061c5/gazebo-2*.log
[INFO] [WallTime: 1476295207.384813] [0.000000] Loading model xml from ros parameter
[INFO] [WallTime: 1476295207.387243] [0.000000] Waiting for service /gazebo/spawn_urdf_model

**Comment by superjax** [comment]
I bet it was my new block laser plugin.  We will probably have to do some work to make sure it works in Gazebo 7.  I commented it out, see if it works for you. I also did do some cleanup to `simple.launch` so that it relies on ros_copter to fly around autonomously.

**Comment by superjax** [comment]
Is this solved?
