### ISSUE TITLE
Errors when running catkin_make

### ISSUE THREAD

**Issue by zamora18** [BYU-MAGICC/fcu_sim#16]
There seems to be a few 'syntax' type errors in the code, particularly in:
1.  gazebo_gimbal_plugin.cpp
   (a) Lines 63, 70, 77, 83:
   This is the error message
         `error: no match for ‘operator<<’ (operand types are ‘gazebo::common::Logger’ and 
         ‘gazebo::common::Logger’)`
   I assume it should just be `gzer << "  ";` instead of `gzer << gzer << "  ";`

      (b) Lines 111-113 and 116-118: 
      These are the error messages
         `error: ‘class gazebo::physics::Joint’ has no member named ‘SetMaxForce’`
         `error: ‘class gazebo::physics::Joint’ has no member named ‘SetAngle’`
   
      (c) Lines 136-138: 
      Error message is similar to (b):
         `error: ‘class gazebo::physics::Joint’ has no member named ‘SetAngle’`

      For errors (b) and (c) I could not find a solution, but when I would comment-out those lines there were 
      no errors 
 
2. gazebo_wind_plugin.cpp
   (a) Line 111
   Error message shows:
      `error: ambiguous overload for ‘operator=’ (operand types are ‘gazebo::math::Vector3’ and ‘<brace-
      enclosed initializer list>’)`
      Though it may not be correct, I changed it to 
           `math::Vector3 wind_direction={wind_x, wind_y, wind_z};`
      and it did not return any errors.

**Comment by superjax** [comment]
I think this should be solved with the Kinetic Pull request.  (For the most part, these were deprecated functionality from Gazebo 2, except for the `gzerr` calls, that was just a mistake.
