### ISSUE TITLE
Gimbal Bug

### ISSUE THREAD

**Issue by zamora18** [BYU-MAGICC/fcu_sim#18]
The autopilot or controller has issues with the gimbal code in junker_base.xacro. When I comment out lines 246-254 it works okay.

**Comment by drinkdhmo** [comment]
Reducing the mass of the gimbal by two orders of magnitude appears to have fixed the issue. In gimbal.xacro I set:
`mass="0.00001"`

I also set the mass tag of each link to be:
`<mass value="${mass}" />`

**Comment by superjax** [comment]
@drinkdhmo, do you think you could create a pull request with that fix?
