### ISSUE TITLE
Plugins using the wrong time for messages

### ISSUE THREAD

**Issue by el3ment** [BYU-MAGICC/fcu_sim#28]
The following files reference `ros::time::now()` which causes faster-than-real-time simulation to fail miserably. These should be changed to use the current simulation time generally with `world->GetSimTime()`

https://github.com/byu-magicc/fcu_sim/blob/RC1.0/fcu_sim_plugins/src/barometer_plugin.cpp#L94

https://github.com/byu-magicc/fcu_sim/blob/RC1.0/fcu_sim_plugins/src/GPS_plugin.cpp#L147

https://github.com/byu-magicc/fcu_sim/blob/RC1.0/fcu_sim_plugins/src/multirotor_forces_and_moments.cpp#L123

**Comment by superjax** [comment]
This was closed in the most recent pull request for fcu_sim
