### ISSUE TITLE
Broken submodule install

### ISSUE THREAD

**Issue by chunga2** [BYU-MAGICC/fcu_sim#47]
Tried to install fcu_sim in catkin workspace but the submodule for ROSflight is broken. It links to https://github.com/byu-magicc/ROSflight.git which goes to https://github.com/rosflight/firmware. However, running "git submodule update --init --recursive" produces:

fatal: reference is not a tree: 38c89c8b10a66069d076d62886bc7ebd1f6304b9
Unable to checkout '38c89c8b10a66069d076d62886bc7ebd1f6304b9' in submodule path 'fcu_sim_plugins/lib/ROSflight'

I then tried to download ROSflight and ROSflight's firmware manually and build them in the workspace. This produced (my username's alex):

####
####
####
####
[  0%] Built target geometry_msgs_generate_messages_py
[  0%] Built target std_msgs_generate_messages_py
[  0%] Built target _rosflight_msgs_generate_messages_check_deps_Attitude
[  0%] Built target _rosflight_msgs_generate_messages_check_deps_Barometer
[  0%] Built target _rosflight_msgs_generate_messages_check_deps_Status
[  0%] Built target _rosflight_msgs_generate_messages_check_deps_RCRaw
[  0%] Built target _rosflight_msgs_generate_messages_check_deps_ParamFile
[  0%] Built target _rosflight_msgs_generate_messages_check_deps_ParamSet
[  0%] Built target _rosflight_msgs_generate_messages_check_deps_Command
[  0%] Built target _rosflight_msgs_generate_messages_check_deps_ParamGet
[  0%] Built target _rosflight_msgs_generate_messages_check_deps_OutputRaw
[  0%] Built target _rosflight_msgs_generate_messages_check_deps_Airspeed
[  0%] Built target _rosflight_msgs_generate_messages_check_deps_GPS
[  0%] Built target std_msgs_generate_messages_nodejs
[  0%] Built target geometry_msgs_generate_messages_nodejs
[  0%] Built target std_msgs_generate_messages_lisp
[  0%] Built target geometry_msgs_generate_messages_lisp
[  0%] Built target std_msgs_generate_messages_cpp
[  0%] Built target geometry_msgs_generate_messages_cpp
[  0%] Built target _rosflight_msgs_generate_messages_check_deps_State
[  0%] Built target std_msgs_generate_messages_eus
[  0%] Built target geometry_msgs_generate_messages_eus
[  0%] Built target trajectory_msgs_generate_messages_py
[  0%] Built target std_srvs_generate_messages_nodejs
[  0%] Built target sensor_msgs_generate_messages_py
[  0%] Built target rosgraph_msgs_generate_messages_cpp
[  0%] Built target roscpp_generate_messages_py
[  0%] Built target rosgraph_msgs_generate_messages_eus
[  0%] Built target std_srvs_generate_messages_py
[  0%] Built target rosgraph_msgs_generate_messages_nodejs
[  0%] Built target roscpp_generate_messages_eus
[  0%] Built target std_srvs_generate_messages_cpp
[  0%] Built target rosgraph_msgs_generate_messages_py
[  0%] Built target roscpp_generate_messages_nodejs
[  0%] Built target rosgraph_msgs_generate_messages_lisp
[  0%] Built target std_srvs_generate_messages_lisp
[  0%] Built target roscpp_generate_messages_lisp
[  0%] Built target sensor_msgs_generate_messages_lisp
[  0%] Built target gazebo_msgs_generate_messages_cpp
[  0%] Built target sensor_msgs_generate_messages_eus
[  0%] Built target gazebo_msgs_generate_messages_lisp
[  0%] Built target sensor_msgs_generate_messages_nodejs
[  0%] Built target gazebo_msgs_generate_messages_eus
[  0%] Built target gazebo_msgs_generate_messages_py
[  0%] Built target std_srvs_generate_messages_eus
[  0%] Built target gazebo_msgs_generate_messages_nodejs
[  0%] Built target sensor_msgs_generate_messages_cpp
[  0%] Built target trajectory_msgs_generate_messages_eus
[  0%] Built target trajectory_msgs_generate_messages_cpp
[  0%] Built target trajectory_msgs_generate_messages_lisp
[  0%] Built target trajectory_msgs_generate_messages_nodejs
[  0%] Built target tf_generate_messages_cpp
[  1%] Built target actionlib_generate_messages_py
[  2%] Built target rosflight_utils
[  2%] Built target actionlib_generate_messages_nodejs
[  2%] Built target tf_generate_messages_py
[  2%] Built target actionlib_msgs_generate_messages_lisp
[  2%] Built target tf2_msgs_generate_messages_cpp
[  2%] Built target actionlib_generate_messages_lisp
[  2%] Built target tf_generate_messages_eus
[  2%] Built target actionlib_msgs_generate_messages_cpp
[  2%] Built target tf_generate_messages_nodejs
[  2%] Built target actionlib_msgs_generate_messages_eus
[  2%] Built target actionlib_generate_messages_cpp
[  2%] Built target actionlib_msgs_generate_messages_nodejs
[  2%] Built target actionlib_msgs_generate_messages_py
[  2%] Built target tf2_msgs_generate_messages_lisp
[  2%] Built target tf_generate_messages_lisp
[  2%] Built target tf2_msgs_generate_messages_nodejs
[  2%] Built target tf2_msgs_generate_messages_eus
[  2%] Built target tf2_msgs_generate_messages_py
[  2%] Built target actionlib_generate_messages_eus
[  2%] Built target bond_generate_messages_lisp
[  2%] Built target dynamic_reconfigure_gencfg
[  2%] Built target dynamic_reconfigure_generate_messages_lisp
[  2%] Built target nav_msgs_generate_messages_py
[  2%] Built target dynamic_reconfigure_generate_messages_eus
[  2%] Built target polled_camera_generate_messages_cpp
[  2%] Built target nav_msgs_generate_messages_lisp
[  2%] Built target dynamic_reconfigure_generate_messages_py
[  2%] Built target nodelet_generate_messages_nodejs
[  2%] Built target nav_msgs_generate_messages_eus
[  2%] Built target nav_msgs_generate_messages_cpp
[  2%] Built target dynamic_reconfigure_generate_messages_nodejs
[  2%] Built target topic_tools_generate_messages_nodejs
[  2%] Built target nodelet_generate_messages_py
[  2%] Built target polled_camera_generate_messages_eus
[  2%] Built target dynamic_reconfigure_generate_messages_cpp
[  2%] Built target bond_generate_messages_py
[  2%] Built target topic_tools_generate_messages_lisp
[  2%] Built target topic_tools_generate_messages_py
[  2%] Built target nav_msgs_generate_messages_nodejs
[  2%] Built target polled_camera_generate_messages_py
[  2%] Built target polled_camera_generate_messages_lisp
[  2%] Built target gazebo_ros_gencfg
[  2%] Built target polled_camera_generate_messages_nodejs
[  2%] Built target gazebo_plugins_gencfg
[  2%] Built target nodelet_generate_messages_cpp
[  2%] Built target bond_generate_messages_nodejs
[  2%] Built target nodelet_generate_messages_eus
[  2%] Built target nodelet_generate_messages_lisp
[  2%] Built target bond_generate_messages_cpp
[  2%] Built target bond_generate_messages_eus
[  2%] Built target topic_tools_generate_messages_cpp
[  2%] Built target topic_tools_generate_messages_eus
[ 15%] Built target rosflight_msgs_generate_messages_py
[ 26%] Built target rosflight_msgs_generate_messages_nodejs
[ 37%] Built target rosflight_msgs_generate_messages_lisp
[ 48%] Built target rosflight_msgs_generate_messages_cpp
[ 60%] Built target rosflight_msgs_generate_messages_eus
[ 60%] Built target rosflight_msgs_generate_messages
[ 60%] Built target roscpp_generate_messages_cpp
[ 61%] Built target joy
[ 63%] Built target step_camera
[ 65%] Built target world_utilities
[ 71%] Built target mavrosflight
[ 73%] Built target fcu_sim_camera_utils
[ 75%] Built target GPS_plugin
[ 77%] Built target multirotor_forces_and_moments_plugin
[ 79%] Built target barometer_plugin
make[2]: *** No rule to make target 'fcu_sim/fcu_sim_plugins/CMakeFiles/ROSflight_sil_plugin.dir/build'.  Stop.
CMakeFiles/Makefile2:6180: recipe for target 'fcu_sim/fcu_sim_plugins/CMakeFiles/ROSflight_sil_plugin.dir/all' failed
make[1]: *** [fcu_sim/fcu_sim_plugins/CMakeFiles/ROSflight_sil_plugin.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 80%] Built target gimbal_plugin
[ 82%] Built target wind_plugin
[ 84%] Built target aircraft_truth_plugin
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
Invoking "make -j4 -l4" failed

I suspect that the git submodule points to and uses an old, moved repo that fcu_sim wants.

**Comment by superjax** [comment]
Sorry, we are in the middle of restructuring `fcu_sim` and haven't yet moved the remote.

I just pushed a change to RC1.0.  Would you give that a go?

**Comment by superjax** [comment]
Okay, I think I just fixed it, would you try again with the latest `RC1.0` branch?

**Comment by superjax** [comment]
by the way, I think the submodules might be all messed up.  You may have to do something like `git submodule sync` after pulling.

**Comment by chunga2** [comment]
OK, I got fixedwing.launch to work; I think that's good. Thanks!
