### ISSUE TITLE
Invalid syntax

### ISSUE THREAD

**Issue by el3ment** [BYU-MAGICC/fcu_sim#9]
https://github.com/byu-magicc/fcu_sim/blob/master/fcu_sim/launch/simple.launch

has name- instead of name=

**Comment by superjax** [comment]
Oops...  I can fix this this evening.  Or, I can make you a collaborator, and you can fix it yourself.  What's easier?

**Comment by el3ment** [comment]
probably just have you fix it this evening - if i find a few more things being a collaborator would make more sense
